accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path(
        "signup/done/",
         views.SignupDoneView.as_view(),
         name="signup_done",
    ),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("logout_confirm/", views.LogoutConfirmView.as_view(), name="logout_confirm"),
    path(
        "nickname_change/<uuid:pk>/",
        views.NicknameChangeView.as_view(),
        name="nickname_change",
    ),
    path(
        "nickname_change/done/",
        views.NicknameChangeDoneView.as_view(),
        name="nickname_change_done",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
]

meproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notice.urls')),
    path('accounts/', include('accounts.urls')),
    path('reminder/', include('reminder.urls')),
]

notice/urls.py
from django.urls import path
from . import views


app_name = "notice"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("index/", views.IndexView.as_view(), name="index"),
    path("about_signup/", views.AboutSignupView.as_view(), name="about_signup"),
    path("terms_of_use/", views.TermsOfUseView.as_view(), name="terms_of_use"),
    path("privacy_policy/", views.PrivacyPolicyView.as_view(), name="privacy_policy"),
]

reminder/urls.py
from django.urls import path
from . import views

app_name = 'reminder'

urlpatterns = [
    path('month/', views.MonthCalendarView.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendarView.as_view(), name='month'),

    path('week/', views.WeekCalendarView.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendarView.as_view(), name='week'),

    path('day/', views.DayCalendarView.as_view(), name='day'),
    path('day/<int:year>/<int:month>/<int:day>/', views.DayCalendarView.as_view(), name='day'),

    path('schedules/', views.ScheduleListView.as_view(), name='schedule_list'),
    path('schedules/list/', views.ScheduleListView.as_view(), name='schedule_list'),
    path('schedules/detail/<int:pk>/', views.ScheduleDetailView.as_view(), name='schedule_detail'),
    path('schedules/create/', views.ScheduleCreateView.as_view(), name='schedule_create'),
    path('schedules/update/<int:pk>/', views.ScheduleUpdateView.as_view(), name='schedule_update'),
    path('schedules/finished/<int:pk>/', views.ScheduleFinishedView.as_view(), name='schedule_finished'),
    path('schedules/unfinished/<int:pk>/', views.ScheduleUnfinishedView.as_view(), name='schedule_unfinished'),
    path('schedules/delete/<int:pk>/', views.ScheduleDeleteView.as_view(), name='schedule_delete'),
]

templates/base/_alert.html
{% if messages %}
<div class="container">
    <div class="row justify-content-center pt-4">
        <div class="col align-self-center">
            <ul class="messages list-unstyled mb-0">
                {% for message in messages %}
                <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endif %}

templates/base/_breadcrumb.html
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb p-3 bg-light rounded-2">
        <li class="breadcrumb-item"><a href="{% url 'notice:index' %}" class="link-success">ホーム</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ breadcrumb }}</li>
    </ol>
</nav>

templates/base/_carousel.html
{% load static %}

<!-- carousel -->
<div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel" data-bs-theme="light">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'images/carousel2.png' %}" class="d-block w-100 animated-background1">
            <div class="container">
                <div class="carousel-caption text-start">
                    <p class="h1 uniwars">More Efficiently.</p>
                    <p class="opacity-75 pb-5 uniwars">Eliminate waste through efficient study and improve your daily life.</p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/carousel2.png' %}" class="d-block w-100 animated-background2">
            <div class="container">
                <div class="carousel-caption">
                    <p class="h1 uniwars">Shared reminder.</p>
                    <p class="opacity-75 pb-5 uniwars">By sharing, there is no problem even if you forget to set the reminder.</p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/carousel2.png' %}" class="d-block w-100 animated-background3">
            <div class="container">
                <div class="carousel-caption text-end">
                    <p class="h1 uniwars">Works with Discord API.</p>
                    <p class="opacity-75 pb-5 uniwars">Discord is used by everyone, and there are many benefits to be gained by linking it together.</p>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<!-- carousel -->

templates/base/_footer.html
<footer class="position-absolute bottom-0 d-flex flex-wrap justify-content-between align-items-center bg-dark py-3 w-100">
    <div class="col-lg-4 d-flex align-items-center">
        <span class="text-white mx-4">&copy; 2024 ME Project</span>
    </div>

    <ul class="nav col-lg-4 justify-content-end list-unstyled d-flex">
        <li class="mx-3">
            <a class="text-white" href="https://github.com/arcsino/meproject" target="_blank">
                <i class="bi bi-github h2"></i>
            </a>
        </li>
    </ul>
</footer>

templates/base/_header.html
{% load static %}

<!-- carousel -->
<div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel" data-bs-theme="light">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'images/carousel2.png' %}" class="d-block w-100 animated-background1">
            <div class="container">
                <div class="carousel-caption text-start">
                    <p class="h1 uniwars">More Efficiently.</p>
                    <p class="opacity-75 pb-5 uniwars">Eliminate waste through efficient study and improve your daily life.</p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/carousel2.png' %}" class="d-block w-100 animated-background2">
            <div class="container">
                <div class="carousel-caption">
                    <p class="h1 uniwars">Shared reminder.</p>
                    <p class="opacity-75 pb-5 uniwars">By sharing, there is no problem even if you forget to set the reminder.</p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/carousel2.png' %}" class="d-block w-100 animated-background3">
            <div class="container">
                <div class="carousel-caption text-end">
                    <p class="h1 uniwars">Works with Discord API.</p>
                    <p class="opacity-75 pb-5 uniwars">Discord is used by everyone, and there are many benefits to be gained by linking it together.</p>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<!-- carousel -->

templates/base/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" aria-label="Offcanvas navbar large">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'notice:index' %}">
            <span class="border-success border-bottom border-2  ms-2 uniwars">me<span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbar2Label">
                    <span class="border-success border-bottom border-2 uniwars">me<span>
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body d-flex flex-column flex-lg-row">
                <ul class="navbar-nav justify-content-start flex-grow-1 pe-3 mb-auto">
                    <li class="nav-item dropdown ms-2">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-info-circle me-2"></i>About
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="{% url 'notice:about_signup' %}">
                                    <i class="bi bi-person-add me-2"></i>サインアップについて
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'notice:terms_of_use' %}">
                                    <i class="bi bi-journal-check me-2"></i>利用規約
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'notice:privacy_policy' %}">
                                    <i class="bi bi-shield-check me-2"></i>プライバシーポリシー
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown ms-2">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person me-2"></i>Account
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:nickname_change' user.pk %}">
                                    <i class="bi bi-tag me-2"></i>ニックネーム変更
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:password_change' %}">
                                    <i class="bi bi-key me-2"></i>パスワード変更
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:logout_confirm' %}">
                                    <i class="bi bi-door-open pe-2"></i>ログアウト
                                </a>
                            </li>
                            {% else %}
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:login' %}">
                                    <i class="bi bi-box-arrow-in-right me-2"></i>ログイン
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:signup' %}">
                                    <i class="bi bi-person-add me-2"></i>サインアップ
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown ms-2">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-bell me-2"></i>Reminder
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="{% url 'reminder:month' %}">
                                    <i class="bi bi-calendar3 me-2"></i>月間カレンダー
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'reminder:week' %}">
                                    <i class="bi bi-calendar3-week me-2"></i>週間カレンダー
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'reminder:day' %}">
                                    <i class="bi bi-calendar3-event me-2"></i>日間カレンダー
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'reminder:schedule_create' %}">
                                    <i class="bi bi-plus-square me-2"></i>スケジュール作成
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'reminder:schedule_list' %}">
                                    <i class="bi bi-check-square me-2"></i>スケジュール一覧
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                <ul class="navbar-nav align-items-center border border-success border-2 px-2 py-3 py-lg-0">
                    <li><i class="bi bi-person-check pe-2"></i>{{ user.nickname }}</li>
                </ul>
                {% else %}
                <ul class="navbar-nav align-items-center border border-warning border-2 px-2 py-3 py-lg-0">
                    <li><i class="bi bi-person-exclamation pe-2"></i>{{ user }}</li>
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

templates/base/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ME - {% block title %}{% endblock %}</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}" sizes="180x180">
    <link rel="icon" type="image/png" href="{% static 'images/android-chrome-192x192.png' %}" sizes="192x192">


    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <!-- Other CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="min-vh-100 position-relative" style="padding-top: 54px;">

    {% include 'base/_navbar.html' %}

    {% block header %}{% endblock %}

    {% block content %}{% endblock %}

    <hr class="border-0 m-0 pt-5">
    <hr class="border-0 m-0 pt-3">

    {% include 'base/_footer.html' %}

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>