accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path(
        "signup/done/",
         views.SignupDoneView.as_view(),
         name="signup_done",
    ),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("logout_confirm/", views.LogoutConfirmView.as_view(), name="logout_confirm"),
    path(
        "nickname_change/<uuid:pk>/",
        views.NicknameChangeView.as_view(),
        name="nickname_change",
    ),
    path(
        "nickname_change/done/",
        views.NicknameChangeDoneView.as_view(),
        name="nickname_change_done",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
]

meproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notice.urls')),
    path('accounts/', include('accounts.urls')),
    path('reminder/', include('reminder.urls')),
]

notice/urls.py
from django.urls import path
from . import views


app_name = "notice"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("index/", views.IndexView.as_view(), name="index"),
    path("about_signup/", views.AboutSignupView.as_view(), name="about_signup"),
    path("terms_of_use/", views.TermsOfUseView.as_view(), name="terms_of_use"),
    path("privacy_policy/", views.PrivacyPolicyView.as_view(), name="privacy_policy"),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
import uuid


class CustomUserManager(BaseUserManager):

    def _create_user(self, username, nickname, password, **extra_fields):
        if not username:
            raise ValueError("この項目は必須です。")
        user = self.model(username=username, nickname=nickname, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, username, nickname, password=None, **extra_fields):
        extra_fields.setdefault('is_active', False)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, nickname, password, **extra_fields)

    def create_superuser(self, username, nickname, password=None, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True

        if extra_fields.get("is_staff") is not True:
            raise ValueError("スーパーユーザーには is_staff=True が必要です。")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("スーパーユーザーには is_superuser=True が必要です。")

        return self._create_user(username, nickname, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。"
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("同じユーザー名が既に登録済みです。"),
        },
    )
    nickname = models.CharField(
        _("ニックネーム"),
        max_length=32,
        help_text=_(
            "この項目はスケジュール完遂ユーザーで公開される名前です。"
        ),
    )
    is_superuser = models.BooleanField(
        _("superuer"),
        default=False,
        help_text=_("ユーザーがスーパーユーザーかどうかを示します。"),
    )
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("ユーザーが管理サイトにログイン可能かどうかを示します。"),
    )
    is_active = models.BooleanField(
        _("active"),
        default=False,
        help_text=_(
            "ユーザーがアクティブかどうかを示します。"
            "アカウントを削除する代わりに選択を解除してください。"
        ),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["nickname",]

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django import forms


User = get_user_model()


class SignupForm(UserCreationForm):
    usable_password = None

    class Meta:
        model = User
        fields = ("username", "nickname", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class NicknameChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("nickname",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class PasswordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from .forms import (
    SignupForm,
    NicknameChangeForm,
    LoginForm,
    PasswordChangeForm,
)


User = get_user_model()


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        account = get_object_or_404(User, pk=self.kwargs["pk"])
        return self.request.user == account


class SignupView(generic.CreateView):
    """ サインアップビュー """
    form_class = SignupForm
    success_url = reverse_lazy("accounts:signup_done")
    template_name = "accounts/signup.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        signup_context = {
            "breadcrumb": "Account - サインアップ",
        }
        context.update(signup_context)
        return context


class SignupDoneView(generic.TemplateView):
    """サインアップ済ビュー"""
    template_name = 'accounts/done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        signup_context = {
            "title": "Sign Up",
            "breadcrumb": "Account - サインアップ",
            "h1": "サインアップが完了しました。",
            "p": "データベース管理者にログイン権限を与えてもらってください。",
        }
        context.update(signup_context)
        return context


class LoginView(LoginView):
    """ログインビュー"""
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_context = {
            "breadcrumb": "Account - ログイン",
        }
        context.update(login_context)
        return context
    
    def form_valid(self, form):
        messages.info(self.request, 'ログインに成功しました。')
        return super().form_valid(form)


class LogoutConfirmView(LoginRequiredMixin, generic.TemplateView):
    """ログアウト確認ビュー"""
    template_name = 'accounts/logout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logout_context = {
            "breadcrumb": "Account - ログアウト",
        }
        context.update(logout_context)
        return context


class LogoutView(LoginRequiredMixin, LogoutView):
    """ログアウトビュー"""
    template_name = 'accounts/login.html'


class NicknameChangeView(LoginRequiredMixin, OnlyYouMixin, generic.UpdateView):
    """ ニックネーム変更ビュー """
    model = User
    form_class = NicknameChangeForm
    success_url = reverse_lazy("accounts:nickname_change_done")
    template_name = "accounts/nickname_change.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nickname_context = {
            "breadcrumb": "Account - ニックネーム変更",
        }
        context.update(nickname_context)
        return context


class NicknameChangeDoneView(generic.TemplateView):
    """サインアップ済ビュー"""
    template_name = 'accounts/done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nickname_context = {
            "title": "Nickname Change",
            "breadcrumb": "Account - ニックネーム変更",
            "h1": "ニックネームを変更しました。",
            "p": "変更したい場合は何度でもできます。",
        }
        context.update(nickname_context)
        return context


class PasswordChangeView(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = PasswordChangeForm
    success_url = reverse_lazy("accounts:password_change_done")
    template_name = 'accounts/password_change.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        password_context = {
            "breadcrumb": "Account - パスワード変更",
        }
        context.update(password_context)
        return context


class PasswordChangeDoneView(PasswordChangeDoneView):
    """パスワード変更済ビュー"""
    template_name = 'accounts/done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        password_context = {
            "title": "Password Change",
            "breadcrumb": "Account - パスワード変更",
            "h1": "パスワードを変更しました",
            "p": "パスワードを忘れた場合は、管理者にパスワードを変更してもらってください。",
        }
        context.update(password_context)
        return context

templates/accounts/discord_command.html
{% extends 'base/base.html' %}

{% block title %}My Discord Command{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">MyDiscordコマンド</span>
            </h1>
            <form method="post">{% csrf_token %}
                {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {% for error in form.non_field_errors %}
                    <p class="mb-0">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
                <table class="table mb-5">
                    <tbody>
                        <tr>
                            <th scope="row"></th>
                            <td></td>
                        </tr>
                        {% for field in form %}
                        <tr>
                            <th scope="row">{{ field.label_tag }}</th>
                            <td>{{ field }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-save me-2"></i>Save
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/done.html
{% extends "base/base.html" %}

{% block title %}{{ title }} Done{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">{{ h1 }}</span>
            </h1>
            <p class="mb-5">{{ p }}</p>
            <a class="btn btn-primary mb-3" href="{% url 'notice:index' %}">
                <i class="bi bi-house pe-2"></i>Back To Home
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'base/base.html' %}

{% block title %}Log In{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">ログイン</span>
            </h1>
            <form method="post">{% csrf_token %}
                {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {% for error in form.non_field_errors %}
                    <p class="mb-0">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
                <table class="table mb-5">
                    <tbody>
                        <tr>
                            <th scope="row"></th>
                            <td></td>
                        </tr>
                        {% for field in form %}
                        <tr>
                            <th scope="row">{{ field.label_tag }}</th>
                            <td>{{ field }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-box-arrow-in-right me-2"></i>Log In
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base/base.html' %}

{% block title %}Log Out{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">ログアウト</span>
            </h1>
            <p class="text-danger mb-5">本当にログアウトしてもいいですか？</p>
            <a class="btn btn-primary mb-3" href="{% url 'notice:index' %}">
                <i class="bi bi-house pe-2"></i>Back To Home
            </a>
            <form action="{% url 'accounts:logout' %}" method="post">{% csrf_token %}
                <button class="btn btn-danger" type="submit">
                    <i class="bi bi-door-open pe-2"></i>Log Out
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/nickname_change.html
{% extends "base/base.html" %}

{% block title %}Nickname Change{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">ニックネーム変更</span>
            </h1>
            <form method="post">{% csrf_token %}
                <table class="table mb-5">
                    <tbody>
                        <tr>
                            <th scope="row"></th>
                            <td></td>
                        </tr>
                        {% for field in form %}
                        <tr>
                            <th scope="row">{{ field.label_tag }}</th>
                            <td>
                                {{ field }}
                                {% if field.help_text %}
                                <small class="form-text">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                <p class="text-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-arrow-repeat me-2"></i>Change Nickname
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/password_change.html
{% extends "base/base.html" %}

{% block title %}Password Change{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">パスワード変更</span>
            </h1>
            <form method="post">{% csrf_token %}
                <table class="table mb-5">
                    <tbody>
                        <tr>
                            <th scope="row"></th>
                            <td></td>
                        </tr>
                        {% for field in form %}
                        <tr>
                            <th scope="row">{{ field.label_tag }}</th>
                            <td>
                                {{ field }}
                                {% if field.help_text %}
                                <small class="form-text">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                <p class="text-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-arrow-repeat me-2"></i>Change Password
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/password_change_done.html
{% extends "base/base.html" %}

{% block title %}Password Change Done{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">パスワードを変更しました</span>
            </h1>
            <p class="mb-5">パスワードを忘れた場合は、管理者にパスワードを変更してもらってください。</p>
            <a class="btn btn-primary mb-3" href="{% url 'notice:index' %}">
                <i class="bi bi-house pe-2"></i>Back To Home
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/password_change_form.html
{% extends "base/base.html" %}

{% block title %}Password Change{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">パスワード変更</span>
            </h1>
            <form method="post">{% csrf_token %}
                <table class="table mb-5">
                    <tbody>
                        <tr>
                            <th scope="row"></th>
                            <td></td>
                        </tr>
                        {% for field in form %}
                        <tr>
                            <th scope="row">{{ field.label_tag }}</th>
                            <td>
                                {{ field }}
                                {% if field.help_text %}
                                <small class="form-text">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                <p class="text-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-arrow-repeat me-2"></i>Change Password
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "base/base.html" %}

{% block title %}Sign Up{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">サインアップ</span>
            </h1>
            <form method="post">{% csrf_token %}
                <table class="table mb-5">
                    <tbody>
                        <tr>
                            <th scope="row"></th>
                            <td></td>
                        </tr>
                        {% for field in form %}
                        <tr>
                            <th scope="row">{{ field.label_tag }}</th>
                            <td>
                                {{ field }}
                                {% if field.help_text %}
                                <small class="form-text">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                <p class="text-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-success">
                    <i class="bi bi-person-add me-2"></i>Sign Up
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}