meproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notice.urls')),
    path('accounts/', include('accounts.urls')),
    path('reminder/', include('reminder.urls')),
]

notice/urls.py
from django.urls import path
from . import views


app_name = "notice"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("index/", views.IndexView.as_view(), name="index"),
    path("about_signup/", views.AboutSignupView.as_view(), name="about_signup"),
    path("terms_of_use/", views.TermsOfUseView.as_view(), name="terms_of_use"),
    path("privacy_policy/", views.PrivacyPolicyView.as_view(), name="privacy_policy"),
]

reminder/urls.py
from django.urls import path
from . import views

app_name = 'reminder'

urlpatterns = [
    path('month/', views.MonthCalendarView.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendarView.as_view(), name='month'),

    path('week/', views.WeekCalendarView.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendarView.as_view(), name='week'),

    path('day/', views.DayCalendarView.as_view(), name='day'),
    path('day/<int:year>/<int:month>/<int:day>/', views.DayCalendarView.as_view(), name='day'),

    path('schedules/', views.ScheduleListView.as_view(), name='schedule_list'),
    path('schedules/list/', views.ScheduleListView.as_view(), name='schedule_list'),
    path('schedules/detail/<int:pk>/', views.ScheduleDetailView.as_view(), name='schedule_detail'),
    path('schedules/create/', views.ScheduleCreateView.as_view(), name='schedule_create'),
    path('schedules/update/<int:pk>/', views.ScheduleUpdateView.as_view(), name='schedule_update'),
    path('schedules/finished/<int:pk>/', views.ScheduleFinishedView.as_view(), name='schedule_finished'),
    path('schedules/unfinished/<int:pk>/', views.ScheduleUnfinishedView.as_view(), name='schedule_unfinished'),
    path('schedules/delete/<int:pk>/', views.ScheduleDeleteView.as_view(), name='schedule_delete'),
]

reminder/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from accounts.models import CustomUser


class Category(models.Model):
    name = models.CharField(
        _("カテゴリー名"),
        max_length=64,
        unique=True,
    )
    bs_color = models.CharField(_("Boostrap Color"), max_length=32)
    bs_icon = models.CharField(_("Bootstrap Icon"), max_length=32)
    webhook_url = models.CharField(_("Webhook Url"), max_length=128)
    embed_color = models.CharField(_("embed_color"), max_length=16, default="green")

    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(
        _("教科名"),
        max_length=64,
        unique=True,
    )
    grade = models.IntegerField(
        _("学年"),
    )

    def __str__(self):
        return self.name


class Deadline(models.Model):
    date = models.DateField(
        _("締め切り日"),
        unique=True,
    )
    MON = "月曜日"
    TUE = "火曜日"
    WED = "水曜日"
    THU = "木曜日"
    FRI = "金曜日"
    SAT = "土曜日"
    SUN = "日曜日"
    WEEK_CHOICES = {
        MON: "月曜日",
        TUE: "火曜日",
        WED: "水曜日",
        THU: "木曜日",
        FRI: "金曜日",
        SAT: "土曜日",
        SUN: "日曜日",
    }
    week = models.CharField(
        _("曜日"),
        max_length=3,
        choices=WEEK_CHOICES,
        default=MON
    )

    def __str__(self):
        return self.date.strftime("%Y年%m月%d日") + f"（{self.week}）"


class Schedule(models.Model):
    category = models.ForeignKey(
        Category,
        verbose_name="カテゴリー名",
        on_delete=models.CASCADE,
    )
    subject = models.ForeignKey(
        Subject,
        verbose_name="教科名",
        on_delete=models.CASCADE,
    )
    title = models.CharField(
        _("タイトル名"),
        max_length=64,
        help_text=_(
            "課題プリント、中間テスト、証明写真など"
        ),
    )
    detail = models.TextField(
        _("詳細"),
        blank=True,
        null=True,
        help_text=_(
            "詳しい説明などはこちらに。空欄でも可。"
        ),
    )
    deadline = models.ForeignKey(
        Deadline,
        verbose_name="締め切り日",
        on_delete=models.CASCADE,
    )
    created_by = models.CharField(
        _("作成者"),
        max_length=64,
        default=_("unknown")
    )
    created_at = models.DateTimeField(
        _("作成日時"),
        auto_now_add=True,
    )
    updated_by = models.CharField(
        _("編集者"),
        max_length=64,
        default=_("unknown"),
    )
    updated_at = models.DateTimeField(
        _("変更日時"),
        auto_now=True,
    )
    finished_user = models.ManyToManyField(
        CustomUser,
        verbose_name="完遂ユーザー",
        blank=True,
    )

    def __str__(self):
        return self.title

reminder/forms.py
from django import forms
from .models import Schedule


class ScheduleCreateForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ('category', 'subject', 'title', 'detail', 'deadline')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.help_text


class ScheduleFinishedForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ()

reminder/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils import timezone
from django.views import generic
from django.urls import reverse_lazy
from .models import Category, Schedule
from .forms import ScheduleCreateForm, ScheduleFinishedForm
from . import mixins
import datetime


class MonthCalendarView(LoginRequiredMixin, mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'reminder/month.html'
    model = Schedule

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class WeekCalendarView(LoginRequiredMixin, mixins.WeekCalendarMixin, generic.TemplateView):
    """週間カレンダーを表示するビュー"""
    template_name = 'reminder/week.html'
    model = Schedule

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class DayCalendarView(LoginRequiredMixin, mixins.DayCalendarMixin, generic.TemplateView):
    """日間カレンダーを表示するビュー"""
    template_name = 'reminder/day.html'
    model = Schedule

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_day_calendar()
        context.update(calendar_context)
        return context


class ScheduleListView(LoginRequiredMixin, generic.TemplateView):
    """スケジュール一覧ビュー"""
    template_name = 'reminder/schedule_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = datetime.date.today()
        homework_context = {
            'breadcrumb': 'Reminder - スケジュール一覧',
            'schedules': Schedule.objects.filter(deadline__date__gte=today).order_by('deadline', 'subject'),
            'categories': Category.objects.order_by('pk'),
            'first_category': Category.objects.first(),
        }
        context.update(homework_context)
        return context


class ScheduleDetailView(LoginRequiredMixin, generic.DetailView):
    """スケジュール詳細を表示するビュー"""
    template_name = 'reminder/schedule_detail.html'
    model = Schedule
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        homework_context = {
            'breadcrumb': 'スケジュール詳細',
            'categories': Category.objects.all(),
        }
        context.update(homework_context)
        return context


class ScheduleCreateView(LoginRequiredMixin, generic.CreateView):
    """スケジュール作成ビュー"""
    model = Schedule
    template_name = 'reminder/schedule_create.html'
    form_class = ScheduleCreateForm
    success_url = reverse_lazy('reminder:schedule_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        create_context = {
            "breadcrumb": "Reminder - スケジュール作成",
        }
        context.update(create_context)
        return context
    
    def form_valid(self, form):
        schedule = form.save(commit=False)
        schedule.created_by = str(self.request.user)
        schedule.updated_by = str(self.request.user)
        schedule.save()
        messages.success(self.request, 'スケジュールを作成しました。')
        return super().form_valid(form)


class ScheduleUpdateView(LoginRequiredMixin, generic.UpdateView):
    """スケジュール編集ビュー"""
    model = Schedule
    template_name = 'reminder/schedule_update.html'
    form_class = ScheduleCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        update_context = {
            "breadcrumb": "スケジュール編集",
        }
        context.update(update_context)
        return context

    def get_success_url(self):
        return reverse_lazy('reminder:schedule_detail', kwargs={'pk': self.kwargs['pk']})
    
    def form_valid(self, form):
        schedule = form.save(commit=False)
        schedule.updated_by = str(self.request.user)
        schedule.save()
        messages.info(self.request, 'スケジュールを更新しました。')
        return super().form_valid(form)


class ScheduleFinishedView(LoginRequiredMixin, generic.UpdateView):
    """スケジュール完遂ビュー"""
    model = Schedule
    template_name = 'reminder/schedule_finished.html'
    form_class = ScheduleFinishedForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        finished_context = {
            "breadcrumb": "スケジュール完遂",
        }
        context.update(finished_context)
        return context

    def get_success_url(self):
        return reverse_lazy("reminder:schedule_detail", kwargs={"pk": self.kwargs["pk"]})
    
    def form_valid(self, form):
        schedule = form.save(commit=False)
        schedule.finished_user.add(self.request.user)
        schedule.save()
        messages.info(self.request, "完遂ユーザーに追加しました。")
        return super().form_valid(form)


class ScheduleUnfinishedView(LoginRequiredMixin, generic.UpdateView):
    """スケジュール未完遂ビュー"""
    model = Schedule
    template_name = 'reminder/schedule_finished.html'
    form_class = ScheduleFinishedForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        finished_context = {
            "breadcrumb": "スケジュール完遂",
        }
        context.update(finished_context)
        return context

    def get_success_url(self):
        return reverse_lazy("reminder:schedule_detail", kwargs={"pk": self.kwargs["pk"]})
    
    def form_valid(self, form):
        schedule = form.save(commit=False)
        schedule.finished_user.remove(self.request.user)
        schedule.save()
        messages.error(self.request, "完遂ユーザーから削除しました。")
        return super().form_valid(form)


class ScheduleDeleteView(LoginRequiredMixin, generic.DeleteView):
    """スケジュール削除ビュー"""
    model = Schedule
    template_name = 'reminder/schedule_delete.html'
    success_url = reverse_lazy('reminder:schedule_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        update_context = {
            "breadcrumb": "スケジュール削除",
        }
        context.update(update_context)
        return context
    
    def form_valid(self, form):
        messages.error(self.request, 'スケジュールを削除しました。')
        return super().form_valid(form)

templates/reminder/day.html
{% extends 'base/base.html' %}

{% block title %}Day Calendar{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-10 align-self-center">
            <h1 class="text-center lh-1 my-5">
                <span class="border-bottom border-success border-2">日間カレンダー</span>
            </h1>
            <nav aria-label="pagination">
                <ul class="pagination justify-content-center">
                    <li class="page-item">
                        <a class="page-link" href="{% url 'reminder:day' day_previous.year day_previous.month  day_previous.day %}">前日</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link disabled">{{ day_current | date:"Y年m月d日" }} ({{ week_name }})</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="{% url 'reminder:day' day_next.year day_next.month  day_next.day %}">次日</a>
                    </li>
                </ul>
            </nav>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="table-secondary">
                        <tr>
                            <th>{{ day_current }} ({{ week_name }})</th>
                        </tr>
                    </thead>
                    {% if now == day_current %}
                    <tbody class="table-success">
                    {% else %}
                    <tbody>
                    {% endif %}
                        <tr>
                            <td>
                                {% if schedules %}
                                    {% for s in schedules %}
                                        {% if s.deadline.date == day_current %}
                                            {% for c in categories %}
                                                {% if s.category.name == c.name %}
                                                <div class="card border-{{ c.bs_color }} my-2">
                                                    <div class="card-header bg-{{ c.bs_color }} text-white">
                                                        <i class="bi {{ c.bs_icon }} me-2"></i>{{ c.name }}
                                                    </div>
                                                    <div class="card-body">
                                                        <h5 class="card-title fw-bold">{{ s.subject.name }}</h5>
                                                        <p class="card-text">{{ s.title }}</p>
                                                        {% if s.detail %}
                                                        <div class="accordion" id="accordionExample">
                                                            <div class="accordion-item">
                                                                <h2 class="accordion-header">
                                                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ s.pk }}" aria-expanded="false" aria-controls="collapse{{ s.pk }}">
                                                                        詳細
                                                                    </button>
                                                                </h2>
                                                                <div id="collapse{{ s.pk }}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                                                                    <div class="accordion-body">{{ s.detail }}</div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reminder/schedule_create.html
{% extends "base/base.html" %}

{% block title %}Schedule Create{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">スケジュール作成</span>
            </h1>
            <form method="post">{% csrf_token %}
                <table class="table mb-5">
                    <tbody>
                        <tr>
                            <th scope="row"></th>
                            <td></td>
                        </tr>
                        {% for field in form %}
                        <tr>
                            <th scope="row">{{ field.label_tag }}</th>
                            <td>
                                {{ field }}
                                {% for error in field.errors %}
                                <p class="text-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-success">
                    <i class="bi bi-plus-square me-2"></i>Create Schedule
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/reminder/schedule_delete.html
{% extends "base/base.html" %}

{% block title %}Password Change Done{% endblock %}

{% block header %}
<!-- breadcrumb -->
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb p-3 bg-light rounded-2">
        <li class="breadcrumb-item"><a href="{% url 'notice:index' %}" class="link-success">ホーム</a></li>
        <li class="breadcrumb-item"><a href="{% url 'reminder:schedule_list' %}" class="link-success">Reminder - スケジュール一覧</a></li>
        <li class="breadcrumb-item"><a href="{% url 'reminder:schedule_detail' object.pk %}" class="link-success">スケジュールの詳細</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ breadcrumb }}</li>
    </ol>
</nav>
<!-- breadcrumb -->

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">スケジュール削除</span>
            </h1>
            <p class="text-danger lead mb-5">本当に削除してもいいですか？</p>
            <p class="mb-5">削除 - スケジュール #{{object.pk}} </p>
            <form method="post">{% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    <i class="bi bi-trash3 me-2"></i>Delete Schedule
                </button>
            </form>
            <a href="{% url 'reminder:schedule_detail' object.pk %}" class="btn btn-primary">Cancel</a>
        </div>
    </div>
</div>
{% endblock %}

templates/reminder/schedule_detail.html
{% extends 'base/base.html' %}

{% block title %}Schedule Detail{% endblock %}

{% block header %}
<!-- breadcrumb -->
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb p-3 bg-light rounded-2">
        <li class="breadcrumb-item"><a href="{% url 'notice:index' %}" class="link-success">ホーム</a></li>
        <li class="breadcrumb-item"><a href="{% url 'reminder:schedule_list' %}" class="link-success">Reminder - スケジュール一覧</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ breadcrumb }}</li>
    </ol>
</nav>
<!-- breadcrumb -->

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center pb-5">
        <div class="col-md-10 align-self-center">
            <h1 class="text-center lh-1 my-5">
                <span class="border-bottom border-success border-2">スケジュール詳細</span>
            </h1>
            {% for c in categories %}
                {% if object.category.name == c.name %}
                <div class="card border-{{ c.bs_color }} my-3">
                    <div class="card-header bg-{{ c.bs_color }} text-white">
                        <i class="bi {{ c.bs_icon }} me-2"></i>{{ c.name }}
                    </div>
                {% endif %}
            {% endfor %}
                <div class="card-body">
                    <div class="row card-text">
                        <div class="col-auto">教科：</div>
                        <div class="col">{{ object.subject.name }}</div>
                    </div>
                    <hr>
                    <div class="row card-text">
                        <div class="col-auto">タイトル：</div>
                        <div class="col">{{ object.title }}</div>
                    </div>
                    <hr>
                    <div class="row card-text">
                        <div class="col-auto">詳細：</div>
                        <div class="col">
                            {% if object.detail %}
                                {{ object.detail }}
                            {% else %}
                                <span class="text-secondary">なし</span>
                            {% endif %}
                        </div>
                    </div>
                    <hr>
                    <div class="row card-text">
                        <div class="col-auto">締め切り日：</div>
                        <div class="col">{{ object.deadline }}</div>
                    </div>
                    <hr>
                    <div class="row card-text">
                        <div class="col-auto">完遂ユーザー：</div>
                        <div class="col">
                            {% for u in object.finished_user.all %}
                            <span class="me-2">{{ u }}</span>
                            {% empty %}
                            <span class="text-secondary">完遂ユーザーはいません。</span>
                            {% endfor %}
                        </div>
                    </div>
                    <hr>
                    <div class="row card-text">
                        <div class="col-auto">作成日時：</div>
                        <div class="col">{{ object.created_at }}</div>
                    </div>
                    <hr>
                    <div class="row card-text">
                        <div class="col-auto">変更日時：</div>
                        <div class="col">{{ object.updated_at }}</div>
                    </div>
                    <hr>
                    <div class="row card-text">
                        <div class="col-auto">スケジュールID：</div>
                        <div class="col">{{ object.pk }}</div>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-end">
                        <div class="btn-group">
                            {% for c in categories %}
                                {% if object.category.name == c.name %}
                                <a href="{% url 'reminder:schedule_update' object.pk %}" class="btn btn-sm btn-outline-{{ c.bs_color }}">編集する</a>
                                    {% if not user in object.finished_user.all %}
                                    <a href="{% url 'reminder:schedule_finished' object.pk %}" class="btn btn-sm btn-outline-{{ c.bs_color }}">完遂ユーザー</a>
                                    {% else %}
                                    <a href="{% url 'reminder:schedule_unfinished' object.pk %}" class="btn btn-sm btn-outline-{{ c.bs_color }}">完遂ユーザー</a>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- detail -->
{% endblock %}

templates/reminder/schedule_list.html
{% extends 'base/base.html' %}

{% block title %}Schedule List{% endblock %}

{% block header %}

    {% include 'base/_breadcrumb.html' %}

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center pb-5">
        <div class="col-md-10 align-self-center">
            <h1 class="text-center lh-1 my-5">
                <span class="border-bottom border-success border-2">スケジュール一覧</span>
            </h1>
            <div class="d-flex justify-content-end mb-4">
                <a href="{% url 'reminder:schedule_create' %}" class="btn btn-outline-success">新規作成</a>
            </div>
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        {% for c in categories %}
                        <li class="nav-item">
                            {% if c == first_category %}
                            <button class="nav-link link-dark active" data-bs-toggle="tab" data-bs-target="#category{{ c.pk }}" type="button">
                                {{ c.name }}
                            </button>
                            {% else %}
                            <button class="nav-link link-dark" data-bs-toggle="tab" data-bs-target="#category{{ c.pk }}" type="button">
                                {{ c.name }}
                            </button>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        {% for c in categories %}
                            {% if c == first_category %}
                            <div class="tab-pane active" id="category{{ c.pk }}">
                            {% else %}
                            <div class="tab-pane" id="category{{ c.pk }}">
                            {% endif %}
                            {% for s in schedules %}
                                {% if s.category.name == c.name %}
                                <div class="card border-{{ c.bs_color }} my-3">
                                    <div class="card-header bg-{{ c.bs_color }} text-white">
                                        {{ s.deadline }}
                                    </div>
                                    <div class="card-body">
                                        <h5 class="card-title fw-bold">{{ s.subject.name }}</h5>
                                        <p class="card-text">{{ s.title }}</p>
                                        {% if s.detail %}
                                        <div class="accordion mb-3" id="accordionExample">
                                            <div class="accordion-item">
                                                <h2 class="accordion-header">
                                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ s.pk }}" aria-expanded="false" aria-controls="collapse{{ s.pk }}">
                                                    詳細
                                                    </button>
                                                </h2>
                                                <div id="collapse{{ s.pk }}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                                                    <div class="accordion-body">{{ s.detail }}</div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endif %}
                                        <div class="btn-group">
                                            <a href="{% url 'reminder:schedule_detail' s.pk %}" class="btn btn-sm btn-outline-{{ c.bs_color }}">もっと見る</a>
                                            <a href="{% url 'reminder:schedule_update' s.pk %}" class="btn btn-sm btn-outline-{{ c.bs_color }}">編集する</a>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reminder/schedule_update.html
{% extends "base/base.html" %}

{% block title %}Schedule Update{% endblock %}

{% block header %}
<!-- breadcrumb -->
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb p-3 bg-light rounded-2">
        <li class="breadcrumb-item"><a href="{% url 'notice:index' %}" class="link-success">ホーム</a></li>
        <li class="breadcrumb-item"><a href="{% url 'reminder:schedule_list' %}" class="link-success">Reminder - スケジュール一覧</a></li>
        <li class="breadcrumb-item"><a href="{% url 'reminder:schedule_detail' object.pk %}" class="link-success">スケジュールの詳細</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ breadcrumb }}</li>
    </ol>
</nav>
<!-- breadcrumb -->

    {% include 'base/_alert.html' %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pb-5">
        <div class="col-md-7 align-self-center">
            <h1 class="lh-1 my-5">
                <span class="border-bottom border-success border-2">スケジュール編集</span>
            </h1>
            <form method="post">{% csrf_token %}
                <table class="table mb-5">
                    <tbody>
                        <tr>
                            <th scope="row"></th>
                            <td></td>
                        </tr>
                        {% for field in form %}
                        <tr>
                            <th scope="row">{{ field.label_tag }}</th>
                            <td>
                                {{ field }}
                                {% for error in field.errors %}
                                <p class="text-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-arrow-repeat me-2"></i>Update Schedule
                </button>
            </form>
            <a href="{% url 'reminder:schedule_delete' object.pk %}" class="btn btn-danger">
                <i class="bi bi-trash3 me-2"></i>Delete Schedule
            </a>
        </div>
    </div>
</div>
{% endblock %}